/* Generated language packs with human-reviewed terminology and UI copy. */
window.__GAME_I18N_SOURCE_LANG__ = "en";
window.__GAME_I18N_PACKS__ = {
  "en": {
    "AUTO MERGE": "AUTO MERGE",
    "BACKGROUNDS": "BACKGROUNDS",
    "Best: Lv.": "Best: Lv.",
    "Box speed upgraded": "Box speed upgraded",
    "Call Lumi": "Call Lumi",
    "CAT COLLECTION": "CAT COLLECTION",
    "Cat moved to a new spot": "Cat moved to a new spot",
    "Change background": "Change background",
    "Clear": "Clear",
    "Close": "Close",
    "Close preview": "Close preview",
    "Coins earned": "Coins earned",
    "Collection": "Collection",
    "COLLECTION": "COLLECTION",
    "COZY CAT MERGE": "COZY CAT MERGE",
    "DECORATE": "DECORATE",
    "Discard": "Discard",
    "Discard furniture": "Discard furniture",
    "Drag to move anywhere. Drop onto an identical to merge, or use Auto merge.": "Drag to move anywhere. Drop onto an identical to merge, or use Auto merge.",
    "FLIP": "FLIP",
    "Flip furniture": "Flip furniture",
    "FURNITURE": "FURNITURE",
    "Lumi": "Lumi",
    "LUMI": "LUMI",
    "Lumi COLLECTION": "Lumi COLLECTION",
    "Match identical Lumi": "Match identical Lumi",
    "No matching Lumi to merge": "No matching Lumi to merge",
    "Not enough coins": "Not enough coins",
    "Open 5 boxes": "Open 5 boxes",
    "OPEN BOX": "OPEN BOX",
    "Open boxes, discover odd cats, and build the purr-fect collection.": "Open boxes, discover odd cats, and build the purr-fect collection.",
    "OWNED": "OWNED",
    "Reach Lv.3": "Reach Lv.3",
    "Reset all progress and start over?": "Reset all progress and start over?",
    "ROOM": "ROOM",
    "Room reset": "Room reset",
    "SHOP": "SHOP",
    "SIZE": "SIZE",
    "SOLD OUT": "SOLD OUT",
    "SPEED UP": "SPEED UP",
    "TODAY'S PURRS": "TODAY'S PURRS"
  },
  "zh-TW": {
    "AUTO MERGE": "自動合成",
    "BACKGROUNDS": "背景",
    "Best: Lv.": "最高：Lv.",
    "Box speed upgraded": "開箱速度已提升",
    "Call Lumi": "呼叫 Lumi",
    "CAT COLLECTION": "貓咪圖鑑",
    "Cat moved to a new spot": "貓咪換了新位置",
    "Change background": "更換背景",
    "Clear": "清除",
    "Close": "關閉",
    "Close preview": "關閉預覽",
    "Coins earned": "獲得金幣",
    "Collection": "圖鑑",
    "COLLECTION": "圖鑑",
    "COZY CAT MERGE": "療癒貓咪合成",
    "DECORATE": "佈置",
    "Discard": "捨棄",
    "Discard furniture": "丟棄家具",
    "Drag to move anywhere. Drop onto an identical to merge, or use Auto merge.": "拖曳可自由移動。放到相同物件上即可合成，或使用「自動合成」。",
    "FLIP": "翻轉",
    "Flip furniture": "翻轉家具",
    "FURNITURE": "家具",
    "Lumi": "Lumi",
    "LUMI": "LUMI",
    "Lumi COLLECTION": "Lumi 收藏圖鑑",
    "Match identical Lumi": "合成相同的 Lumi",
    "No matching Lumi to merge": "找不到可合成的相同 Lumi",
    "Not enough coins": "金幣不足",
    "Open 5 boxes": "開啟 5 個箱子",
    "OPEN BOX": "開箱",
    "Open boxes, discover odd cats, and build the purr-fect collection.": "開啟箱子、發現古怪又可愛的貓咪，打造最療癒的收藏。",
    "OWNED": "已擁有",
    "Reach Lv.3": "達到 Lv.3",
    "Reset all progress and start over?": "要重置所有進度並重新開始嗎？",
    "ROOM": "房間",
    "Room reset": "房間已重置",
    "SHOP": "商店",
    "SIZE": "大小",
    "SOLD OUT": "已售完",
    "SPEED UP": "加速",
    "TODAY'S PURRS": "今日呼嚕",
    "LUMI COLLECTION": "Lumi 收藏圖鑑",
    "family": "家族"
  },
  "zh-CN": {
    "AUTO MERGE": "自动合成",
    "BACKGROUNDS": "背景",
    "Best: Lv.": "最高：Lv.",
    "Box speed upgraded": "开箱速度已提升",
    "Call Lumi": "呼叫 Lumi",
    "CAT COLLECTION": "猫咪图鉴",
    "Cat moved to a new spot": "猫咪换了新位置",
    "Change background": "更换背景",
    "Clear": "清除",
    "Close": "关闭",
    "Close preview": "关闭预览",
    "Coins earned": "获得金币",
    "Collection": "图鉴",
    "COLLECTION": "图鉴",
    "COZY CAT MERGE": "治愈猫咪合成",
    "DECORATE": "布置",
    "Discard": "丢弃",
    "Discard furniture": "丢弃家具",
    "Drag to move anywhere. Drop onto an identical to merge, or use Auto merge.": "拖动可自由移动。放到相同物件上即可合成，或使用“自动合成”。",
    "FLIP": "翻转",
    "Flip furniture": "翻转家具",
    "FURNITURE": "家具",
    "Lumi": "Lumi",
    "LUMI": "LUMI",
    "Lumi COLLECTION": "Lumi 收藏图鉴",
    "Match identical Lumi": "合成相同的 Lumi",
    "No matching Lumi to merge": "找不到可合成的相同 Lumi",
    "Not enough coins": "金币不足",
    "Open 5 boxes": "开启 5 个箱子",
    "OPEN BOX": "开箱",
    "Open boxes, discover odd cats, and build the purr-fect collection.": "开启箱子、发现古怪又可爱的猫咪，打造最治愈的收藏。",
    "OWNED": "已拥有",
    "Reach Lv.3": "达到 Lv.3",
    "Reset all progress and start over?": "要重置所有进度并重新开始吗？",
    "ROOM": "房间",
    "Room reset": "房间已重置",
    "SHOP": "商店",
    "SIZE": "大小",
    "SOLD OUT": "已售罄",
    "SPEED UP": "加速",
    "TODAY'S PURRS": "今日呼噜",
    "LUMI COLLECTION": "Lumi 收藏图鉴",
    "family": "家族"
  },
  "ja": {
    "AUTO MERGE": "自動マージ",
    "BACKGROUNDS": "背景",
    "Best: Lv.": "ベスト：Lv.",
    "Box speed upgraded": "開封速度がアップしました",
    "Call Lumi": "Lumiを呼ぶ",
    "CAT COLLECTION": "ネコ図鑑",
    "Cat moved to a new spot": "ネコが新しい場所へ移動しました",
    "Change background": "背景を変更",
    "Clear": "クリア",
    "Close": "閉じる",
    "Close preview": "プレビューを閉じる",
    "Coins earned": "獲得コイン",
    "Collection": "図鑑",
    "COLLECTION": "図鑑",
    "COZY CAT MERGE": "ほっこりネコマージ",
    "DECORATE": "模様替え",
    "Discard": "手放す",
    "Discard furniture": "家具を処分する",
    "Drag to move anywhere. Drop onto an identical to merge, or use Auto merge.": "ドラッグで自由に移動できます。同じものに重ねてマージするか、「自動マージ」を使いましょう。",
    "FLIP": "反転",
    "Flip furniture": "家具を反転",
    "FURNITURE": "家具",
    "Lumi": "Lumi",
    "LUMI": "LUMI",
    "Lumi COLLECTION": "Lumi コレクション",
    "Match identical Lumi": "同じLumiをマージ",
    "No matching Lumi to merge": "マージできる同じLumiがいません",
    "Not enough coins": "コインが足りません",
    "Open 5 boxes": "箱を5個開ける",
    "OPEN BOX": "箱を開ける",
    "Open boxes, discover odd cats, and build the purr-fect collection.": "箱を開けて、ちょっと変わったネコたちを集め、自分だけの最高のコレクションを作りましょう。",
    "OWNED": "所持済み",
    "Reach Lv.3": "Lv.3に到達",
    "Reset all progress and start over?": "進行状況をすべてリセットして最初からやり直しますか？",
    "ROOM": "部屋",
    "Room reset": "部屋をリセットしました",
    "SHOP": "ショップ",
    "SIZE": "サイズ",
    "SOLD OUT": "売り切れ",
    "SPEED UP": "スピードアップ",
    "TODAY'S PURRS": "今日のゴロゴロ",
    "LUMI COLLECTION": "Lumi コレクション",
    "family": "ファミリー"
  }
};
